theme: jekyll-theme-minimal
title: Help Johnny Glue
description: john fundraiser site
lsi: false
safe: true
source: help-johnny-glue
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
