theme: jekyll-theme-cayman
title: Support Johnny Glue AKA John Green
description: Help John get back on his feet
lsi: false
safe: true
source: help-john-green
incremental: false
highlighter: rouge
gist:
  noscript: true
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
github:
  is_project_page: false
