theme: jekyll-theme-cayman
title: Support Johnny Glue
description: Help John get back on his feet
lsi: false
safe: true
source: help-johnny-glue
incremental: false
highlighter: rouge
gist:
  noscript: true
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
